// Generated by gencpp from file robot_mind/next_target_location.msg
// DO NOT EDIT!


#ifndef ROBOT_MIND_MESSAGE_NEXT_TARGET_LOCATION_H
#define ROBOT_MIND_MESSAGE_NEXT_TARGET_LOCATION_H

#include <ros/service_traits.h>


#include <robot_mind/next_target_locationRequest.h>
#include <robot_mind/next_target_locationResponse.h>


namespace robot_mind
{

struct next_target_location
{

typedef next_target_locationRequest Request;
typedef next_target_locationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct next_target_location
} // namespace robot_mind


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_mind::next_target_location > {
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::robot_mind::next_target_location&) { return value(); }
};

template<>
struct DataType< ::robot_mind::next_target_location > {
  static const char* value()
  {
    return "robot_mind/next_target_location";
  }

  static const char* value(const ::robot_mind::next_target_location&) { return value(); }
};


// service_traits::MD5Sum< ::robot_mind::next_target_locationRequest> should match 
// service_traits::MD5Sum< ::robot_mind::next_target_location > 
template<>
struct MD5Sum< ::robot_mind::next_target_locationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_mind::next_target_location >::value();
  }
  static const char* value(const ::robot_mind::next_target_locationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_mind::next_target_locationRequest> should match 
// service_traits::DataType< ::robot_mind::next_target_location > 
template<>
struct DataType< ::robot_mind::next_target_locationRequest>
{
  static const char* value()
  {
    return DataType< ::robot_mind::next_target_location >::value();
  }
  static const char* value(const ::robot_mind::next_target_locationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_mind::next_target_locationResponse> should match 
// service_traits::MD5Sum< ::robot_mind::next_target_location > 
template<>
struct MD5Sum< ::robot_mind::next_target_locationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_mind::next_target_location >::value();
  }
  static const char* value(const ::robot_mind::next_target_locationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_mind::next_target_locationResponse> should match 
// service_traits::DataType< ::robot_mind::next_target_location > 
template<>
struct DataType< ::robot_mind::next_target_locationResponse>
{
  static const char* value()
  {
    return DataType< ::robot_mind::next_target_location >::value();
  }
  static const char* value(const ::robot_mind::next_target_locationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MIND_MESSAGE_NEXT_TARGET_LOCATION_H
