(cl:defpackage robot_expe-srv
  (:use )
  (:export
   "NEXTTARGETLOCATION"
   "<NEXTTARGETLOCATION-REQUEST>"
   "NEXTTARGETLOCATION-REQUEST"
   "<NEXTTARGETLOCATION-RESPONSE>"
   "NEXTTARGETLOCATION-RESPONSE"
  ))

