(cl:defpackage robot_mind-srv
  (:use )
  (:export
   "NEXTTARGETLOCATION"
   "<NEXTTARGETLOCATION-REQUEST>"
   "NEXTTARGETLOCATION-REQUEST"
   "<NEXTTARGETLOCATION-RESPONSE>"
   "NEXTTARGETLOCATION-RESPONSE"
  ))

